server:
    port: 8080

spring:
    datasource:
        url: jdbc:mysql://127.0.0.1:3306/adminstudent?characterEncoding=UTF-8
        username: root
        password: root
        driverClassName: com.mysql.jdbc.Driver

mybatis:
    typeAliasesPackage: com.suixingpay.model.po
    mapperLocations: classpath:com.suixingpay.model.mapper/*.xml